class AppStrings {
  static Map<String, Map<String, String>> localizedValues = {
    'ar': {
      'app_title': 'صلّح | SALLIH',
      'sub_title': 'منصة صيانة المنزل المعتمدة بالكامل',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب جديد',
      'google_login': 'تسجيل الدخول باستخدام Google',
      'or_via_phone': 'أو عبر الجوال / البريد',
      'phone_or_email': 'رقم الجوال أو البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgot_password': 'نسيت كلمة المرور؟',
      'proceed_nafath': 'المتابعة إلى نفاذ (Nafath)',
      'no_account': 'ليس لديك حساب بعد؟',
      'have_account': 'لديك حساب بالفعل؟',
      'full_name': 'الاسم الكامل',
      'national_id': 'رقم الهوية الوطنية / الإقامة',
      'phone_number': 'رقم الجوال',
      'email': 'البريد الإلكتروني',
      'agree_terms': 'أوافق على شروط الخدمة وسياسة الخصوصية',
      'nafath_title': 'التحقق عبر نفاذ (Nafath)',
      'nafath_national': 'النفاذ الوطني الموحد',
      'nafath_code_prompt': 'الرقم المطلوب اختياره في تطبيق نفاذ:',
      'nafath_timer': 'ينتهي الطلب خلال:',
      'nafath_steps': 'خطوات التوثيق والتحقق:',
      'nafath_confirm': 'تأكيد الموافقة في تطبيق نفاذ',
      'nafath_verified': 'موثق في نفاذ',
      'cancel': 'إلغاء',
      'home_tab': 'الرئيسية',
      'orders_tab': 'طلباتي',
      'wallet_tab': 'المحفظة والعناوين',
      'support_tab': 'الضمان والدعم',
      'search_hint': 'ابحث عن خدمة صيانة (سباكة، تكييف، كهرباء...)',
      'categories': 'التصنيفات الرئيسية',
      'all': 'الكل',
      'services_available': 'الخدمات المتاحة للطلب',
      'request_service': 'طلب الخدمة',
      'wallet_balance': 'رصيد المحفظة',
      'cashback': 'مكافآت الكاش باك المكتسبة:',
      'topup': 'شحن المحفظة',
      'addresses': 'عناويني المسجلة',
      'add_address': 'إضافة عنوان',
      'warranty_support': 'دعم صلّح والضمان',
      'submit_ticket': 'إرسال التذكرة لفريق الدعم',
    },
    'en': {
      'app_title': 'SALLIH | صلّح',
      'sub_title': 'Certified Home Maintenance Platform',
      'login': 'Sign In',
      'register': 'Create New Account',
      'google_login': 'Sign In with Google',
      'or_via_phone': 'Or via Phone / Email',
      'phone_or_email': 'Phone Number or Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'proceed_nafath': 'Proceed to Nafath',
      'no_account': "Don't have an account?",
      'have_account': 'Already have an account?',
      'full_name': 'Full Name',
      'national_id': 'National ID / Iqama',
      'phone_number': 'Phone Number',
      'email': 'Email Address',
      'agree_terms': 'I agree to the Terms of Service & Privacy Policy',
      'nafath_title': 'Nafath Verification',
      'nafath_national': 'National Single Sign-On',
      'nafath_code_prompt': 'Select this code in Nafath App:',
      'nafath_timer': 'Request expires in:',
      'nafath_steps': 'Verification Steps:',
      'nafath_confirm': 'Confirm Approval in Nafath App',
      'nafath_verified': 'Verified via Nafath',
      'cancel': 'Cancel',
      'home_tab': 'Home',
      'orders_tab': 'My Orders',
      'wallet_tab': 'Wallet & Addresses',
      'support_tab': 'Warranty & Support',
      'search_hint': 'Search maintenance services (Plumbing, AC, Electrical...)',
      'categories': 'Categories',
      'all': 'All',
      'services_available': 'Available Services',
      'request_service': 'Request Service',
      'wallet_balance': 'Wallet Balance',
      'cashback': 'Cashback Rewards:',
      'topup': 'Top Up Wallet',
      'addresses': 'Saved Addresses',
      'add_address': 'Add Address',
      'warranty_support': 'SALLIH Support & Warranty',
      'submit_ticket': 'Submit Support Ticket',
    },
  };

  static String getString(String key, String langCode) {
    return localizedValues[langCode]?[key] ?? localizedValues['ar']?[key] ?? key;
  }
}
