const phraseCatalog = <String, String>{
  "صلّح | SALLIH": "SALLIH | صلّح",
  "عربي": "عربي",
  "جارٍ تسجيل الدخول بواسطة جوجل...": "Opening Google sign-in…",
  "الرجاء إدخال رقم الجوال أو البريد الإلكتروني": "Enter your phone number or email",
  "أدخل بياناتك أو سجل عبر حساب جوجل للمتابعة.": "Enter your details to continue.",
  "05XXXXXXXX أو example@domain.com": "05XXXXXXXX or example@domain.com",
  "تم إرسال رابط إعادة ضبط كلمة المرور إلى جوالك": "Password reset is not connected yet.",
  "الرجاء تعبئة الحقول الأساسية لإنشاء الحساب": "Complete the required fields",
  "الرجاء الموافقة على الشروط والأحكام لاستكمال التسجيل": "Accept the terms to continue",
  "مرحباً بك في صلّح": "Welcome to SALLIH",
  "أنشئ حسابك للوصول إلى كافة خدمات الصيانة والضمان المعتمد.": "Create an account to access maintenance services.",
  "الاسم الكامل *": "Full name *",
  "مثال: عبدالله الشمري": "Example: Abdullah",
  "رقم الهوية الوطنية / الإقامة *": "National ID / Iqama *",
  "رقم الجوال *": "Phone number *",
  "أوافق على شروط الخدمة وسياسة الخصوصية لمنصة صلّح SALLIH": "I accept the SALLIH terms and privacy policy",
  "إنشاء الحساب والمتابعة لنفاذ": "Create account and continue",
  "طلباتي - صلّح SALLIH": "My orders • SALLIH",
  "لا توجد طلبات في هذه القائمة حالياً": "No orders here yet",
  "مُرسل": "Submitted",
  "جارٍ البحث": "Searching",
  "تم المعاينة": "Inspected",
  "في الطريق 📍": "On the way 📍",
  "وصل الفني": "Technician arrived",
  "قيد التنفيذ": "In progress",
  "مكتمل": "Completed",
  "ملغي": "Cancelled",
  "التفاصيل والخيارات": "Details and options",
  "تم قبول عرض السعر بنجاح وتأكيد الاتفاقية": "Quote accepted",
  "شكراً لك! تم تسليم تقييمك بنجاح وقيد ضمان الخدمة.": "Thank you! Your review has been saved locally.",
  "مُرسل (قيد المراجعة)": "Submitted (under review)",
  "جارٍ البحث عن أفضل مؤسسة وفني": "Finding a service provider",
  "تم قبول الطلب وتعيين المنفذ": "Order accepted and technician assigned",
  "الفني في الطريق إليك الآن (تتبع حي)": "Technician on the way",
  "وصل الفني إلى الموقع": "Technician arrived at the address",
  "الخدمة قيد التنفيذ والعمل": "Service in progress",
  "اكتملت الخدمة بنجاح": "Service completed",
  "تم إلغاء الطلب": "Order cancelled",
  "الحالة الحالية": "Current status",
  "التتبع الحي لموقع الفني": "Technician location",
  "مباشر Live": "Live",
  "الوقت التقديري للوصول: 8 دقائق": "Estimated arrival: 8 minutes",
  "مخطط متابعة الطلب (Timeline)": "Order timeline",
  "الفني المكلف": "Assigned technician",
  "المؤسسة المنفذة": "Service provider",
  "الفني": "Technician",
  "عرض السعر المقدم (Quote)": "Service quote",
  "تم القبول": "Accepted",
  "قيد الانتظار": "Pending",
  "أجور أيدي العاملين:": "Labour:",
  "قطع الغيار والمواد:": "Parts and materials:",
  "ضريبة القيمة المضافة (15%):": "VAT (15%):",
  "الإجمالي الشامل:": "Total:",
  "تم رفض عرض السعر وإرجاع الطلب للبحث": "Quote declined",
  "رفض العرض": "Decline quote",
  "قبول عرض السعر": "Accept quote",
  "تفاصيل الخدمة والموقع": "Service and address",
  "محادثة الفني والمؤسسة": "Contact the technician",
  "الدفع الإلكتروني وإصدار الإيصال": "Pay securely",
  "إضافة تقييم للخدمة": "Review service",
  "⚙️ شريط محاكاة رحلة الطلب للتحقق من النظام:": "Demo: simulate the order journey",
  "تعيين الفني": "Assign technician",
  "في الطريق (تتبع)": "On the way",
  "إكمال وتجهيز الفاتورة": "Complete order",
  "تقييم الخدمة والفني": "Review the service",
  "كيف كانت تجربتك مع تنفيذ الطلب؟": "How was your experience?",
  "اكتب ملاحظاتك وتقييمك للفني والمؤسسة...": "Share your feedback…",
  "إرسال التقييم": "Submit review",
  "النظام": "System",
  "أنت": "You",
  "تم استلام رسالتك، شكراً لك.": "Message received. Thank you.",
  "مرحباً بك! تم فتح المحادثة المباشرة الخاصة بالطلب. المحادثة محمية ومخصصة لتنسيق تنفيذ الخدمة.": "Demo conversation for coordinating your service.",
  "السلام عليكم، أنا في الطريق إليك حالياً وسأصل خلال 10 دقائق بإذن الله.": "Hello! I am on my way and expect to arrive in 10 minutes.",
  "هذه المحادثة مشفرة ومحمية بخصوصية الطلب وفق سياسة صلّح SALLIH": "Demo conversation • messages are stored locally",
  "تم اختيار صورة لإرسالها بالمحادثة": "Image attachment is not connected yet",
  "اكتب رسالتك للفني...": "Write a message…",
  "لا توجد إشعارات جديدة حالياً": "No new notifications",
  "أهلاً بك في منصة صلّح المعتمدة": "Your home, in good hands",
  "نضمن لك جودة التنفيذ وضمان الخدمة عبر فنيين ومؤسسات موثقة برقم نفاذ.": "Explore home maintenance services, all in one place.",
  "التصنيفات الرئيسية": "Service categories",
  "الخدمات المتاحة للطلب": "Explore services",
  "لم نجد خدمات تطابق بحثك": "No matching services",
  "سعر ثابت": "Fixed price",
  "نطاق سعر": "Price range",
  "معاينة / عرض سعر": "Request a quote",
  "التكلفة المقدرة": "Estimated cost",
  "العنوان وموقع الخدمة *": "Service address *",
  "وصف تفصيلي للمشكلة *": "Describe the issue *",
  "اكتب تفاصيل لمساعدة الفني في التشخيص والمعدات المطلوبة...": "Describe the issue to help the technician prepare…",
  "إرفاق صور/فيديو للمشكلة (اختياري)": "Attachments (optional)",
  "تم اختيار صورة توضيحية للمشكلة": "Attachments are not connected yet",
  "رفع صورة من المعرض أو الكاميرا": "Add a photo",
  "المطابقة التلقائية مع أسرع مؤسسة متاحة": "Automatic provider matching",
  "سيقوم النظام باختيار التغطية الأنسب لمنطقتك": "Find a provider covering your area",
  "جدولة الطلب لموعد لاحق": "Schedule for later",
  "الموعد: غداً الساعة 10:00 صباحاً": "Tomorrow at 10:00 AM (demo)",
  "طلب فوري الآن": "Request now",
  "الرجاء إدخال وصف المشكلة": "Describe the issue first",
  "تأكيد وإرسال الطلب": "Confirm request",
  "مطالبة بالضمان (Warranty Claim)": "Warranty claim",
  "شكوى على الفني أو المؤسسة": "Provider complaint",
  "مشكلة في الدفع أو الفاتورة": "Payment or invoice issue",
  "استفسار عام": "General enquiry",
  "الرجاء إدخال تفاصيل البلاغ أو المطالبة بالضمان": "Enter the details of your enquiry",
  "تم فتح التذكرة بنجاح": "Demo ticket created",
  "حسناً": "OK",
  "دعم صلّح والضمان - SALLIH Support": "Support • SALLIH",
  "جميع الخدمات المنفذة عبر صلّح مغطاة بضمان الخدمة المعتمد. يمكنك رفع مطالبة ضمان أو بلاغ في أي وقت.": "Contact support about a service or warranty enquiry.",
  "اختر الطلب المرتبط بالبلاغ/الضمان *": "Related order *",
  "نوع البلاغ / المطالبة *": "Enquiry type *",
  "تفاصيل المشكلة والأدلة *": "Details *",
  "اكتب وصفاً تفصيلياً للمشكلة الحاصلة بعد تنفيذ الخدمة...": "Describe what happened…",
  "تم إرفاق صورة العطل أو الإثبات للضمان": "Attachments are not connected yet",
  "إرفاق صور أو مقطع فيديو توضيحي (Object Storage)": "Add evidence",
  "سباكة": "Plumbing",
  "كهرباء": "Electrical",
  "تكييف وتبريد": "Air conditioning",
  "نظافة وتطهير": "Cleaning",
  "دهانات وديكور": "Painting and decor",
  "أجهزة منزلية": "Appliances",
  "تسريب مياه إصلاح عام": "Water leak repair",
  "فحص وإصلاح تسريبات الأنابيب والحنفيات والوصلات الرئيسية.": "Inspect and repair leaking pipes, taps and connections.",
  "تركيب أدوات صحية": "Bathroom fixture installation",
  "تركيب خلاطات، مغاسل، أو كراسي حمام مع التثبيت والضمان.": "Install taps, sinks and bathroom fixtures.",
  "صيانة وتعبئة فريون مكيف سبليت": "Split AC maintenance",
  "غسيل الوحدة الخارجية والداخلية وتعبئة غاز الفريون الأصلي.": "Clean indoor and outdoor AC units and refill refrigerant.",
  "تأسيس وإصلاح أعطال الكهرباء": "Electrical repairs",
  "معاينة القواطع والأفياش وإصلاح الشورت الكهربائي.": "Inspect breakers and outlets and repair electrical faults.",
  "حسب معاينة الفني (عرض سعر)": "Subject to inspection and quote",
  "المنزل - الرياض": "Home • Riyadh",
  "المكتب": "Office",
  "حي الملقا، طريق أنس بن مالك، مبنى 14": "Al Malqa, Anas Bin Malik Road, Building 14",
  "حي العليا، طريق الملك فهد، برج 3": "Al Olaya, King Fahd Road, Tower 3",
  "عبدالله السعيد": "Abdullah Al Saeed",
  "عبدالله الشمري": "Abdullah Al Shammari",
  "أحمد محمود": "Ahmed Mahmoud",
  "خالد السعيد": "Khaled Al Saeed",
  "سعد علي": "Saad Ali",
  "مؤسسة التبريد المتقدم للصيانة": "Advanced Cooling Maintenance",
  "مؤسسة السباكة الحديثة": "Modern Plumbing",
  "مؤسسة صيانة الرياض الفنية": "Riyadh Maintenance",
  "مؤسسة الخدمة السريعة": "Quick Service",
  "المكيف يخرج هواء حار مع صوت مرتفع من الوحدة الخارجية": "AC blows hot air and the outdoor unit is noisy",
  "انسداد في مجرى المطبخ الرئيسي": "Blocked kitchen drain",
  "تركيب 2 خلاط مغسلة جديد": "Install two sink taps",
  "خدمة ممتازة وسريعة جداً وشغل نظيف": "Excellent, fast and tidy service",
  "منصة صيانة المنزل المعتمدة بالكامل": "Certified Home Maintenance Platform",
  "تسجيل الدخول": "Sign In",
  "إنشاء حساب جديد": "Create New Account",
  "تسجيل الدخول باستخدام Google": "Sign In with Google",
  "أو عبر الجوال / البريد": "Or via Phone / Email",
  "رقم الجوال أو البريد الإلكتروني": "Phone Number or Email",
  "كلمة المرور": "Password",
  "نسيت كلمة المرور؟": "Forgot Password?",
  "المتابعة إلى نفاذ (Nafath)": "Proceed to Nafath",
  "لديك حساب بالفعل؟": "Already have an account?",
  "الاسم الكامل": "Full Name",
  "رقم الهوية الوطنية / الإقامة": "National ID / Iqama",
  "رقم الجوال": "Phone Number",
  "البريد الإلكتروني": "Email Address",
  "أوافق على شروط الخدمة وسياسة الخصوصية": "I agree to the Terms of Service & Privacy Policy",
  "التحقق عبر نفاذ (Nafath)": "Nafath verification (demo)",
  "النفاذ الوطني الموحد": "National single sign-on (demo)",
  "الرقم المطلوب اختياره في تطبيق نفاذ:": "Demo code:",
  "ينتهي الطلب خلال:": "Request expires in:",
  "خطوات التوثيق والتحقق:": "Demo verification steps:",
  "تأكيد الموافقة في تطبيق نفاذ": "Continue demo",
  "موثق في نفاذ": "Verified via Nafath",
  "إلغاء": "Cancel",
  "الرئيسية": "Home",
  "طلباتي": "My Orders",
  "المحفظة والعناوين": "Wallet & Addresses",
  "الضمان والدعم": "Warranty & Support",
  "ابحث عن خدمة صيانة (سباكة، تكييف، كهرباء...)": "Search maintenance services (Plumbing, AC, Electrical...)",
  "الكل": "All",
  "طلب الخدمة": "Request Service",
  "رصيد المحفظة": "Wallet Balance",
  "مكافآت الكاش باك المكتسبة:": "Cashback Rewards:",
  "شحن المحفظة": "Top Up Wallet",
  "عناويني المسجلة": "Saved Addresses",
  "إضافة عنوان": "Add Address",
  "دعم صلّح والضمان": "SALLIH Support & Warranty",
  "إرسال التذكرة لفريق الدعم": "Submit Support Ticket",
  "حدد موقع الخدمة": "Choose your service location",
  "اضغط على الخريطة لاختيار الموقع، أو استخدم موقعك الحالي.": "Tap the map to choose a location, or use your current location.",
  "استخدام موقعي الحالي": "Use my current location",
  "تأكيد الموقع": "Confirm location",
  "فتح الإعدادات": "Open settings",
  "موقع مختار يدويًا": "Manually selected location",
  "اسم العنوان": "Address name",
  "العنوان التفصيلي والحي": "Street, building and neighbourhood",
  "هذا الحقل مطلوب": "This field is required",
  "حفظ العنوان": "Save address",
  "تم حفظ العنوان على هذا الجهاز.": "Address saved on this device.",
  "تعذر حفظ العنوان. أعد المحاولة.": "Unable to save the address. Try again.",
  "الدفع مقابل الخدمة": "Service payments",
  "ادفع من صفحة تفاصيل الطلب عبر مزود دفع آمن. شحن المحفظة غير متاح حاليًا.": "Pay from your order using secure hosted checkout. Wallet top-ups are currently unavailable.",
  "العناوين محفوظة على هذا الجهاز. العناوين الافتراضية بيانات توضيحية.": "Addresses are stored on this device. Default addresses are sample data.",
  "خدمات منزلك في مكان واحد": "Home services, all in one place",
  "أدخل بريدًا إلكترونيًا صالحًا": "Enter a valid email address",
  "إظهار كلمة المرور": "Show password",
  "إخفاء كلمة المرور": "Hide password",
  "استكشاف النسخة التجريبية": "Explore the demo",
  "وضع العرض لا ينفذ دفعًا أو توثيق نفاذ حقيقيًا.": "Demo mode does not process payments or verify Nafath identities.",
  "نسخة تجريبية • البيانات توضيحية": "Demo mode • sample data",
  "تسجيل الدخول الحقيقي غير مهيأ. استخدم وضع العرض فقط.": "Live sign-in is not configured. Explore the demo instead.",
  "إعداد تسجيل الدخول غير صالح.": "Invalid authentication configuration.",
  "تعذر تسجيل الدخول. تحقق من البريد وكلمة المرور.": "Unable to sign in. Check your email and password.",
  "تعذر الاتصال. تحقق من الشبكة وأعد المحاولة.": "Connection failed. Check your network and try again.",
  "راجع بريدك لتأكيد الحساب، ثم سجّل الدخول.": "Check your email to confirm your account, then sign in.",
  "تعذر إنشاء الحساب. تحقق من البيانات أو حاول لاحقًا.": "Unable to create your account. Check your details or try later.",
  "استخدم كلمة مرور من 12 حرفًا على الأقل": "Use a password with at least 12 characters",
  "تعذر تحميل الطلبات. أعد المحاولة.": "Unable to load orders. Try again.",
  "إعادة المحاولة": "Retry",
  "خدمة الدفع غير مهيأة بعد.": "The payment service is not configured yet.",
  "سجّل الدخول بحساب حقيقي للمتابعة.": "Sign in to a real account to continue.",
  "يجب أن يستخدم الخادم اتصال HTTPS.": "The server must use HTTPS.",
  "انتهت الجلسة. سجّل الدخول مجددًا.": "Session expired. Sign in again.",
  "الطلب غير موجود في الخادم. الطلبات التجريبية لا تقبل الدفع.": "Order not found. Demo orders cannot accept payments.",
  "تعذر إكمال العملية. حاول مجددًا أو تواصل مع الدعم.": "Unable to complete the request. Try again or contact support.",
  "رابط الدفع غير صالح.": "Invalid checkout URL.",
  "دفع آمن": "Secure payment",
  "ستدخل بيانات البطاقة في صفحة مزود الدفع الآمنة. لا يحفظ التطبيق بيانات بطاقتك.": "Enter card details on the payment provider’s secure page. This app does not store your card details.",
  "فتح صفحة الدفع": "Open secure checkout",
  "التحقق من حالة الدفع": "Check payment status",
  "بعد الدفع، عد إلى التطبيق للتحقق. الرجوع من صفحة الدفع وحده لا يؤكد نجاح العملية.": "Return to the app to verify payment. Returning from checkout alone does not confirm payment.",
  "تعذر فتح صفحة الدفع.": "Unable to open checkout.",
  "لم يؤكد الخادم الدفع بعد. انتظر قليلًا ثم أعد التحقق.": "Payment has not been confirmed yet. Wait a moment, then check again.",
  "أكد الخادم نجاح الدفع.": "Payment confirmed by the server.",
  "خدمة الموقع متوقفة. فعّلها ثم أعد المحاولة.": "Location services are disabled. Enable them and try again.",
  "إذن الموقع محظور. فعّله من إعدادات التطبيق.": "Location permission is blocked. Enable it in app settings.",
  "لم تمنح إذن الموقع. يمكنك اختيار الموقع يدويًا.": "Location permission denied. You can choose a location manually.",
  "انتهت مهلة تحديد الموقع. حاول في مكان مفتوح أو اختر الموقع يدويًا.": "Location request timed out. Try outdoors or select a location manually.",
  "تعذر تحديد الموقع. تحقق من الإذن والاتصال أو اختر الموقع يدويًا.": "Unable to locate you. Check permissions and connectivity or select a location manually.",
  "عرض موقع الخدمة": "View service location",
  "موقع الخدمة": "Service location",
  "تتبع الفني غير متصل بعد.": "Technician tracking is not connected yet.",
  "محاكاة نفاذ فقط • لم يحدث توثيق حقيقي": "Nafath demo only • no identity verification took place",
  "افتح تطبيق نفاذ (Nafath) على هاتفك المحمول.": "This screen simulates the Nafath flow.",
  "سوف يصلك إشعار طلب دخول وتوثيق حساب من تطبيق صلّح.": "No real Nafath notification will be sent.",
  "إلغاء وإعادة المحاولة": "Cancel and retry",
  "أضف عنوانًا حقيقيًا من صفحة العناوين قبل إنشاء الطلب.": "Add a real address before creating an order.",
  "تسجيل الخروج": "Sign out",
  "طلب تجريبي محلي": "Local demo request",
  "تم إنشاء تذكرة تجريبية محلية. لم تُرسل إلى فريق الدعم.": "Local demo ticket created. It has not been sent to support.",
  "النموذج الحالي تجريبي ولا يرسل تذاكر الدعم إلى خادم.": "This demo form does not submit support tickets to a server.",
  "إرفاق الصور غير متصل بعد.": "Photo attachments are not connected yet.",
  "محادثة تجريبية محلية": "Local demo conversation",
  "إنشاء تذكرة تجريبية": "Create demo ticket",
  "تم إنشاء تذكرة تجريبية": "Demo ticket created",
  "تم حفظ تقييمك محليًا.": "Your review has been saved locally.",
  "تعذر تحميل الخريطة. تحقق من الاتصال وأعد المحاولة.": "Map tiles could not load. Check your connection and retry.",
  "دقة الموقع منخفضة. تحقق من العلامة أو اختر الموقع يدويًا.": "Location accuracy is low. Check the marker or select a location manually."
};
